services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: harshit@20002
      POSTGRES_USER: harshit
      POSTGRES_DB: money-order
    ports:
      - "5432:5432"
    volumes:
      - money_order_data:/var/lib/postgresql/data

volumes:
  money_order_data: