services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: harshit@20002
      POSTGRES_USER: harshit
      POSTGRES_DB: money-order
    ports:
      - "5432:5432"
    volumes:
      - money_order_data:/var/lib/postgresql/data
  mailhog:
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - 1025:1025
      - 8025:8025
volumes:
  money_order_data: